[project]
name = "music-player-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mkdocs[i18n]>=1.6.1",
    "mkdocs-material>=9.5.36",
]
